// Pure history helpers. Opening a page or moving the curriculum day is not activity.
export const historyKinds=['read','review','dictation','answer','selfcheck','speaking','followup'];
export function localDay(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function validDay(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00');return !Number.isNaN(+d)&&localDay(d)===s;}
export function validHistory(map){return !!map&&typeof map==='object'&&!Array.isArray(map)&&Object.entries(map).every(([id,e])=>id.length<200&&!['__proto__','constructor','prototype'].includes(id)&&e&&e.id===id&&historyKinds.includes(e.kind)&&Number.isFinite(e.at)&&e.at>=0&&validDay(e.date)&&Number.isInteger(e.day)&&e.day>=0&&e.day<90&&['card','topic','en','zh','type'].every(k=>typeof e[k]==='string'&&e[k].length<=12000)&&(e.kind!=='review'||['again','hard','good'].includes(e.rating))&&(e.kind!=='dictation'||typeof e.correct==='boolean'));}
export function eventList(map){return Object.values(map).sort((a,b)=>a.at-b.at);}
export function dayStats(events){const unique=(kind,filter=()=>true)=>new Set(events.filter(e=>e.kind===kind&&filter(e)).map(e=>`${e.day}:${e.card}`)).size;return {words:unique('read',e=>e.type==='word'),sentences:unique('read',e=>e.type!=='word'),review:unique('review'),dictation:unique('dictation',e=>e.correct),attempts:events.filter(e=>e.kind==='dictation').length,speaking:events.filter(e=>e.kind==='speaking').length,followup:events.filter(e=>e.kind==='followup').length};}
export function dictationStats(events){const first=new Map();let total=0,correct=0;for(const e of events)if(e.kind==='dictation'){total++;if(e.correct)correct++;const key=`${e.day}:${e.card}`;if(!first.has(key))first.set(key,e);}const entries=[...first.values()];return {total,correct,first:entries.length,firstCorrect:entries.filter(e=>e.correct).length,retries:total-entries.length};}
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={read:'標記已讀',review:'複習',dictation:'聽寫',answer:'編輯個人回答',selfcheck:'口說自評',speaking:'完成口說練習',followup:'完成追問練習'};
const ratings={again:'還不會',hard:'不太熟',good:'記住了'};
export function historyView(store,topics,month,selected,now=new Date()){
 const events=eventList(store.history),today=localDay(now),active=new Set(events.map(e=>e.date));
 const monday=new Date(now.getFullYear(),now.getMonth(),now.getDate()-((now.getDay()+6)%7));
 const week=Array.from({length:7},(_,i)=>localDay(new Date(monday.getFullYear(),monday.getMonth(),monday.getDate()+i)));
 const daily=events.filter(e=>e.date===selected),stats=dayStats(daily),todayStats=dayStats(events.filter(e=>e.date===today)),ds=dictationStats(events);
 const [year,m]=month.split('-').map(Number),offset=(new Date(year,m-1,1).getDay()+6)%7,days=new Date(year,m,0).getDate();
 const latest=new Map(),latestDictation=new Map(),again=new Map();
 for(const e of events){if(e.kind==='review'){latest.set(e.card,e);if(e.rating==='again')again.set(e.card,(again.get(e.card)||0)+1);}if(e.kind==='dictation')latestDictation.set(`${e.day}:${e.card}`,e);}
 const counts={again:0,hard:0,good:0};for(const e of latest.values())counts[e.rating]++;
 const due=Object.values(store.bookmarks).filter(c=>(store.srs[c.id]?.due||0)<=+now).length;
 const wrong=[...latestDictation.values()].filter(e=>!e.correct).sort((a,b)=>b.at-a.at).slice(0,3);
 const repeated=[...latest.values()].filter(e=>e.rating!=='good'&&(again.get(e.card)||0)>=2).slice(0,3);
 const unfinished=topics.filter(t=>!String(store.answers[t.id]||'').trim()).slice(0,3);
 return `<button data-page="plan">← 回到 My Plan</button><section class="hero"><div class="eyebrow">LEARNING JOURNEY</div><h1>看見每一步累積。</h1><p class="muted">學習歷程 · 實際練習，而不只是翻到第幾天。</p></section>
 <div class="metrics card"><div><strong>${active.size}</strong><small>累積練習天數</small></div><div><strong>${week.filter(d=>active.has(d)).length} / 7</strong><small>本週一至日</small></div><div><strong>${todayStats.words+todayStats.sentences+todayStats.review+todayStats.dictation}</strong><small>今日已讀／複習／答對項次</small></div></div>
 <p class="notice">詳細歷程自 ${safe(store.historyStarted||today)} 起記錄。舊收藏與完成紀錄保留；無法回推舊版每日活動與答錯次數。空白日代表「無記錄」，不表示沒有學習。</p>
 <section class="card"><div class="row"><h2>學習日曆</h2><span class="chip">${active.size} 天有記錄</span></div><div class="row history-month"><button data-month="-1" aria-label="上個月">‹</button><h3>${year} 年 ${m} 月</h3><button data-month="1" aria-label="下個月" ${month>=today.slice(0,7)?'disabled':''}>›</button></div><div class="history-calendar">${['一','二','三','四','五','六','日'].map(d=>`<span class="caption">${d}</span>`).join('')}${'<span></span>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const d=`${month}-${String(i+1).padStart(2,'0')}`;return `<button data-history-date="${d}" class="${active.has(d)?'has-activity':''}" aria-pressed="${d===selected}" aria-label="${d} ${active.has(d)?'有練習紀錄':'無紀錄'}" ${d>today?'disabled':''}>${i+1}${active.has(d)?'<span aria-hidden="true">●</span>':''}</button>`}).join('')}</div>
 <h3 class="history-detail-title">${safe(selected)}${selected===today?' · 今天':''}</h3><div class="wrap"><span class="chip">已讀單字 ${stats.words}</span><span class="chip">已讀句子 ${stats.sentences}</span><span class="chip">複習 ${stats.review}</span><span class="chip">聽寫答對 ${stats.dictation}</span><span class="chip">口說 ${stats.speaking} 次</span><span class="chip">追問 ${stats.followup} 次</span></div><p class="caption">同日、同課程日、同題、同活動只算一項；同一題的閱讀／複習／聽寫分開計數。口說以完成按鈕或成功錄音記錄。</p>
 ${daily.length?`<details><summary>查看當日 ${daily.length} 筆活動（最近 30 筆）</summary><ol class="history-events">${daily.slice(-30).reverse().map(e=>`<li><small>${new Date(e.at).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})} · Day ${e.day+1}</small><div>${names[e.kind]}${e.kind==='review'?' · '+ratings[e.rating]:e.kind==='dictation'?' · '+(e.correct?'答對':'再試一次'):''}</div><small>${safe(e.en||topics.find(t=>t.id===e.topic)?.title||'練習')}</small></li>`).join('')}</ol></details>`:'<p class="empty">這天還沒有活動紀錄。完成練習後就會出現在這裡。</p>'}</section>
 <section class="card"><h2>聽寫表現</h2><div class="metrics"><div><strong>${ds.first?Math.round(ds.firstCorrect/ds.first*100)+'%':'—'}</strong><small>首次答對率</small></div><div><strong>${ds.firstCorrect} / ${ds.first}</strong><small>首次答對／已嘗試題目</small></div><div><strong>${ds.retries}</strong><small>再次作答次數</small></div></div><p class="caption">每個課程日的每題，以首次有記錄的作答計算。重新練習不重置歷程。總作答 ${ds.total} 次，其中 ${ds.correct} 次答對；尚未作答不算答錯。</p></section>
 <section class="card"><h2>目前熟悉程度</h2><div class="wrap">${Object.entries(counts).map(([k,n])=>`<span class="chip">${ratings[k]} ${n}</span>`).join('')}<span class="chip">到期收藏 ${due}</span></div><p class="caption">依各題最新一次有記錄的自評分類，不代表客觀面試能力。舊版未留評語的項目不推測分類。</p></section>
 <section class="card focus"><h2>下一步，先練這些</h2>${due?`<p>${due} 個收藏已到期。</p><button data-history-due="true">開始到期複習</button>`:''}${wrong.map(e=>`<p>最近仍答錯：${safe(e.en)}</p><button data-history-practice="${safe(e.card)}" data-course-day="${e.day}">重練這一組聽寫</button>`).join('')}${repeated.map(e=>`<p>反覆還不會：${safe(e.en)}</p><button data-history-review="${safe(e.card)}">再複習這一項</button>`).join('')}${unfinished.length?`<p>還沒寫個人回答：</p><div class="wrap">${unfinished.map(t=>`<button data-open-topic="${t.id}">${safe(t.title)}</button>`).join('')}</div>`:''}${!due&&!wrong.length&&!repeated.length&&!unfinished.length?'<p>目前沒有未解決的聽寫錯題或待寫回答，選一個主題練習脫稿回答與追問。</p><button data-page="interview">前往面試題庫</button>':''}</section>
 <section class="card"><h2>14 個主題準備狀況</h2><p class="caption">個人回答、口說自評、實際追問練習分開記錄；勾選「能回答追問」不等於練過追問。</p><div class="topicList">${topics.map(t=>`<button data-open-topic="${t.id}">${safe(t.title)}<small>個人回答：${String(store.answers[t.id]||'').trim()?'已填寫':'尚未填寫'}</small><small>口說自評：${(store.confidence[t.id]||[]).length}/3 項勾選</small><small>追問練習：${events.filter(e=>e.kind==='followup'&&e.topic===t.id).length} 次</small></button>`).join('')}</div></section><p class="caption">歷程只保存在此裝置／瀏覽器，匯出學習紀錄時一併備份。匯入相同備份不重複計數。</p>`;
}
