import {localDay,validDay,validHistory,historyView} from './learning-history.js?v=9';
import {topics,commonGlossary,phraseTranslations,extraGlossary} from './interview-content.js?v=8';
const KEY='idEnglishStudio.v1',OLD='idInterviewEnglishState';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={audio:'<path d="M11 5 6 9H3v6h3l5 4V5Z"/><path d="M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',bookmark:'<path d="M6 3h12v18l-6-4-6 4V3Z"/>',today:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18"/>',interview:'<path d="M4 3h16v13H9l-5 5V3Z"/>',review:'<path d="M4 8a8 8 0 1 1 0 8M4 3v5h5"/>',practice:'<rect x="8" y="3" width="8" height="12" rx="4"/><path d="M5 11v1a7 7 0 0 0 14 0v-1M12 19v3m-4 0h8"/>',plan:'<path d="M5 4h14v17H5zM9 3h6v3H9zM8 11h8M8 16h5"/>'};
const svg=name=>`<svg class="${name}" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.bookmark}</svg>`;
let store;try{store=JSON.parse(localStorage.getItem(KEY)||'null')}catch{};
if(!store||typeof store!=='object'||Array.isArray(store))store={version:1,route:14,day:0,bookmarks:{},srs:{},reviews:{},practice:{},answers:{},confidence:{},learned:{},interviewDate:''};
for(const k of ['bookmarks','srs','reviews','practice','answers','confidence','learned','history'])if(!store[k]||typeof store[k]!=='object'||Array.isArray(store[k]))store[k]={};
if(![14,30,90].includes(store.route))store.route=14;
store.day=Number.isInteger(store.day)?Math.max(0,Math.min(store.route-1,store.day)):0;
if(!validHistory(store.history))store.history={};
if(!validDay(store.historyStarted))store.historyStarted=localDay();
let historyMonth=localDay().slice(0,7),historyDate=localDay();
function track(kind,c={},extra={}){
 const event={id:crypto.randomUUID(),kind,at:Date.now(),date:localDay(),day:store.day,card:c.id||getTopic().id,topic:c.topic||getTopic().id,en:c.en||'',zh:c.zh||'',type:c.type||'topic',...extra};
 if(kind==='read'&&Object.values(store.history).some(e=>e.kind===kind&&e.date===event.date&&e.day===event.day&&e.card===event.card))return;
 store.history[event.id]=event;
}
function history(){return historyView(store,topics,historyMonth,historyDate);}
const dayKey=id=>`day${store.day}:${id}`;
// Old progress remains untouched under its original key; no destructive migration.
let storageWarning=false;function save(){try{localStorage.setItem(KEY,JSON.stringify(store));return true}catch{storageWarning=true;toast('此裝置無法儲存。請匯出備份，避免關閉後遺失。');return false}}
let page='today',topicId=topics[store.day%topics.length]?.id||'intro',difficulty=store.day>=28?'advanced':'basic',reviewSource='today',reviewType='all',practiceType='word',session=null,translation=null,recording=null,recordUrl=null,recordSeconds=0,recordTimer=null,recordPending=false,recordExtension='webm';
const dictionary={...commonGlossary,...extraGlossary};topics.forEach(t=>t.vocab.forEach(v=>dictionary[v[0].toLowerCase()]=v[1]));
const getTopic=()=>topics.find(t=>t.id===topicId)||topics[0],current=()=>topics[store.day%topics.length];
const dateStamp=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const split=s=>s.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map(x=>x.trim())||[s];
function phrases(t){const en=split(t.basic),zh=phraseTranslations[t.id];return Array.from({length:3},(_,i)=>({en:en[i]||split(t.reply)[0],zh:zh[i]||t.replyzh}));}
function cards(t){return [...t.vocab.map((v,i)=>({id:`${t.id}:word:${i}`,type:'word',en:v[0],zh:v[1],topic:t.id,source:t.title})),...t.vocab.map((v,i)=>({id:`${t.id}:example:${i}`,type:'example',en:v[2],zh:v[3],topic:t.id,source:t.title})),...phrases(t).map((p,i)=>({id:`${t.id}:phrase:${i}`,type:'phrase',...p,topic:t.id,source:t.title}))]}
function allCards(){return topics.flatMap(t=>[...cards(t),...['basic','advanced'].map(level=>({id:`${t.id}:answer:${level}`,type:'answer',en:t[level],zh:t[level+'zh'],topic:t.id,source:t.title})),{id:`${t.id}:question`,type:'question',en:t.q,zh:t.qzh,topic:t.id,source:t.title},{id:`${t.id}:follow`,type:'question',en:t.follow,zh:t.followzh,topic:t.id,source:t.title},{id:`${t.id}:reply`,type:'answer',en:t.reply,zh:t.replyzh,topic:t.id,source:t.title}])}
function cardFor(id){return allCards().find(c=>c.id===id)||store.bookmarks[id]}
const typeLabel={word:'單字',example:'例句',phrase:'回答句',answer:'面試回答',question:'面試問題'};
function words(text){return String(text).split(/([A-Za-z]+(?:[-'][A-Za-z]+)*)/g).map((s,i)=>i%2?`<button class="token" data-word="${esc(s)}">${esc(s)}</button>`:esc(s)).join('')}
function tools(c){return `<div class="tools"><button class="icon" data-audio="${esc(c.en)}" aria-label="播放：${esc(c.en)}">${svg('audio')}</button><button class="icon" data-bookmark="${esc(c.id)}" aria-label="收藏${typeLabel[c.type]||'內容'}：${esc(c.en)}" aria-pressed="${Boolean(store.bookmarks[c.id])}">${svg('bookmark')}</button></div>`}
function unit(c,showZh=true){return `<article class="unit" data-kind="${esc(c.type)}"><div class="row"><div class="unit-copy"><div class="en" data-context="${esc(c.zh)}">${words(c.en)}</div>${showZh?`<p class="translation">${esc(c.zh)}</p>`:''}</div>${tools(c)}</div></article>`}
function toast(s){$('#toast').textContent=s;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').textContent='',3500)}
function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();document.querySelectorAll('.speaking').forEach(b=>{b.classList.remove('speaking');b.removeAttribute('aria-busy')})}
function speak(text,button){if(!('speechSynthesis'in window))return toast('此瀏覽器不支援英文發音。');if(button?.classList.contains('speaking'))return stopSpeech();stopSpeech();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=store.slow?.75:.95;const v=speechSynthesis.getVoices().find(v=>v.lang==='en-US');if(v)u.voice=v;button?.classList.add('speaking');button?.setAttribute('aria-busy','true');u.onend=u.onerror=()=>{button?.classList.remove('speaking');button?.removeAttribute('aria-busy')};speechSynthesis.speak(u)}
function bookmark(id){const c=cardFor(id);if(!c)return;if(store.bookmarks[id]){delete store.bookmarks[id];toast('已取消收藏')}else{store.bookmarks[id]={...c,savedAt:Date.now()};toast('已加入我的重點，今天即可複習')}save();document.querySelectorAll('[data-bookmark]').forEach(b=>b.setAttribute('aria-pressed',String(Boolean(store.bookmarks[b.dataset.bookmark]))));if(page==='review'&&!session)render();}
function lookup(word,context){let root=word.toLowerCase();let meaning=dictionary[root];if(!meaning){const options=[root.replace(/s$/,''),root.replace(/ies$/,'y'),root.replace(/ed$/,''),root.replace(/d$/,''),root.replace(/ing$/,''),root.replace(/ing$/,'e')];root=options.find(x=>dictionary[x])||root;meaning=dictionary[root]}
 translation={id:`lookup:${root}`,type:'word',en:root,zh:meaning||'此單字尚未收錄',topic:getTopic().id,source:'點字查詢'};
 $('#wordBody').innerHTML=`<div class="eyebrow">即時詞義 · 離線可用</div><h2 id="wordTitle" tabindex="-1">${esc(word)}</h2><p class="big">${esc(meaning||'詞義待補充')}</p>${root!==word.toLowerCase()?`<p>原形：${esc(root)}</p>`:''}<div class="word-actions"><button data-audio="${esc(word)}" class="icon" aria-label="播放 ${esc(word)}">${svg('audio')}</button>${meaning?`<button data-action="saveLookup" class="word-save">${svg('bookmark')}<span>收藏這個單字</span></button>`:''}</div>${context?`<div class="notice">句意參考：${esc(context)}</div>`:''}`;$('#wordDialog').showModal();$('#wordTitle').focus({preventScroll:true});}
function hero(k,title,sub){return `<section class="hero"><div class="eyebrow">${k}</div><h1>${title}</h1><p class="muted">${sub}</p></section>`}
function navigation(){const navs=[['today','Today','今日'],['interview','Interview','面試'],['review','Review','複習'],['practice','Practice','練習'],['plan','My Plan','計畫']];$('#nav').innerHTML=navs.map(([id,en,zh])=>`<button data-page="${id}" aria-label="${en} ${zh}" title="${en} · ${zh}" ${(page===id||(page==='history'&&id==='plan'))?'aria-current="page"':''}>${svg(id)}<span>${en}</span><small>${zh}</small></button>`).join('')}
function today(){const t=current(),cs=cards(t),done=cs.filter(c=>store.learned[dayKey(c.id)]).length;const cycle=Math.floor(store.day/14)+1;const remaining=store.interviewDate?Math.ceil((new Date(store.interviewDate+'T00:00:00')-new Date(dateStamp()+'T00:00:00'))/86400000):null;return hero(`DAY ${store.day+1} / ${store.route} · ${remaining===null?'20 MIN DAILY':remaining>=0?'距面試 '+remaining+' 天':'面試日期已過'}`,esc(t.title),'今天的目標：用自己的經歷回答「'+esc(t.q)+'」')+`<div class="wrap"><span class="chip">第 ${cycle} 輪 · ${cycle===1?'理解與跟讀':cycle===2?'收起稿件再回答':'進階回答與追問'}</span><span class="chip">已讀 ${done} / 13</span><button data-action="slow" aria-pressed="${!!store.slow}">語速：${store.slow?'慢速':'正常'}</button></div><div class="progress"><span style="width:${done/13*100}%"></span></div><p class="caption">點英文查中文，喇叭播放，書籤加入跨天複習。</p><section class="card"><div class="row"><h2>01 / 實用單字</h2><span class="chip">5 words</span></div>${cs.filter(c=>c.type==='word').map((c,i)=>unit(c)+unit(cs[5+i])+`<button data-learned="${c.id}" aria-pressed="${!!store.learned[dayKey(c.id)]}">${store.learned[dayKey(c.id)]?'已讀單字':'標記已讀單字'}</button> <button data-learned="${cs[5+i].id}" aria-pressed="${!!store.learned[dayKey(cs[5+i].id)]}">${store.learned[dayKey(cs[5+i].id)]?'已讀例句':'標記已讀例句'}</button>`).join('')}</section><section class="card"><h2>02 / 回答句練習 · 3</h2>${cs.filter(c=>c.type==='phrase').map(c=>unit(c)+`<button data-learned="${c.id}" aria-pressed="${!!store.learned[dayKey(c.id)]}">${store.learned[dayKey(c.id)]?'已讀':'標記已讀'}</button>`).join('')}</section><section class="card focus"><div class="eyebrow">03 / 今日面試對答</div><h2>${esc(t.q)}</h2><p>${esc(t.qzh)}</p><button class="primary" data-open-topic="${t.id}">閱讀對答與練習回答</button><p class="caption">先聽 → 跟讀 → 遮住答案 → 換成自己的經歷</p></section><div class="split"><button data-page="review">複習今日全部 13 項</button><button data-page="practice">開始聽寫與口說</button></div><div class="footer"><button data-day="${store.day-1}" ${store.day===0?'disabled':''}>上一天</button><span>${store.day+1} / ${store.route}</span><button data-day="${store.day+1}" ${store.day===store.route-1?'disabled':''}>下一天</button></div>`}
function interview(){const t=getTopic();const answer=cardFor(`${t.id}:answer:${difficulty}`);return hero('INTERVIEW LIBRARY','把你的故事說清楚。','14 組經典問題 · 工業設計與實體產品設計')+`<label for="topicSelect">選擇面試主題</label><select id="topicSelect">${topics.map(t=>`<option value="${t.id}" ${topicId===t.id?'selected':''}>${t.category} / ${t.title}</option>`).join('')}</select><div class="tabs"><button data-difficulty="basic" class="${difficulty==='basic'?'selected':''}">基礎版 · 簡單短句</button><button data-difficulty="advanced" class="${difficulty==='advanced'?'selected':''}">進階版 · 過程與判斷</button><button data-action="slow">${store.slow?'慢速':'正常'}播放</button></div><div class="notice">以下為虛構示範。請替換成真實作品、責任與成果。</div><section class="card"><div class="speaker">INTERVIEWER / 面試官</div>${unit(cardFor(t.id+':question'))}<div class="speaker">CANDIDATE / 候選人</div>${unit(answer)}<div class="speaker">FOLLOW-UP / 追問</div>${unit(cardFor(t.id+':follow'))}<div class="speaker">CANDIDATE / 延伸回答</div>${unit(cardFor(t.id+':reply'))}</section><section class="card focus"><h2>回答重點</h2><p>${esc(t.coach)}</p><label for="personalAnswer">換成我的經歷（自動儲存）</label><textarea id="personalAnswer" rows="6" placeholder="寫下你的職務、專案與個人貢獻…">${esc(store.answers[t.id]||'')}</textarea><p class="caption">先寫關鍵點，再練到不用看稿。${store.answers[t.id]?'已有你的回答。':''}</p><button class="primary" data-action="goSpeaking">開始口說與自評</button></section>`}
function reviewPool(){let list=reviewSource==='today'?cards(current()):Object.values(store.bookmarks);if(reviewSource==='due')list=list.filter(c=>(store.srs[c.id]?.due||0)<=Date.now());return list.filter(c=>reviewType==='all'||(reviewType==='sentence'?c.type!=='word':c.type==='word'))}
function review(){const pool=reviewPool();return hero('REVIEW','讓重點留在腦中。','你新收藏的內容會立即加入，離線也可以複習。')+`<div class="tabs">${[['today','今日內容'],['saved','我的重點'],['due','今天該複習']].map(([id,label])=>`<button data-source="${id}" class="${reviewSource===id?'selected':''}">${label}</button>`).join('')}</div><div class="tabs">${[['all','全部'],['word','單字'],['sentence','句子與對答']].map(([id,label])=>`<button data-reviewtype="${id}" class="${reviewType===id?'selected':''}">${label}</button>`).join('')}</div>${session?reviewSession():`<section class="card"><div class="row"><h2>${pool.length} 項待練習</h2><button data-action="startReview" class="primary" ${!pool.length?'disabled':''}>開始本輪</button></div><p class="caption">${reviewSource==='today'?'5 個單字 + 5 個例句 + 3 個回答句，每一項都會出題。':'收藏跨天保存，不會因完成複習而自動取消。'}</p>${!pool.length?'<div class="empty">目前沒有內容。<br>在 Today 或 Interview 按書籤加入重點；到期內容會出現在這裡。</div>':pool.map(c=>`<div class="unit"><small>${esc(c.source)} · ${typeLabel[c.type]||'重點'}${store.srs[c.id]?` · 下次 ${new Date(store.srs[c.id].due).toLocaleDateString('zh-TW')}`:''}</small>${unit(c)}</div>`).join('')}</section>`}`}
function reviewSession(){const c=session.queue[session.index];if(!c)return `<section class="card empty"><div class="eyebrow">SESSION COMPLETE</div><h2>本輪 ${session.unique.length} 項已全部練過。</h2><p>完成不會取消收藏；下一次時間已儲存。</p><button data-action="endReview">回到複習清單</button></section>`;return `<section class="card"><div class="row"><span class="chip">第 ${session.index+1} / ${session.queue.length} 題</span><button data-action="endReview">結束本輪</button></div><p class="caption">${esc(c.source)} · ${typeLabel[c.type]} · ${session.unique.length} 個不同項目</p><p class="big">${esc(c.zh)}</p><p class="muted">先試著說英文，再顯示答案。</p>${session.revealed?unit(c,false):'<button class="primary" data-action="reveal">顯示答案</button>'}<div class="rating"><button data-rating="again" ${session.revealed?'':'disabled'}>還不會</button><button data-rating="hard" ${session.revealed?'':'disabled'}>不太熟</button><button data-rating="good" class="primary" ${session.revealed?'':'disabled'}>記住了</button></div><p class="caption">還不會：本輪稍後再練 · 不太熟：明天 · 記住了：3／7／14／30 天後</p></section>`}
function rate(value){if(!session?.revealed)return;const c=session.queue[session.index],old=store.srs[c.id]||{level:0};const level=value==='good'?Math.min((old.level||0)+1,4):0;const days=value==='good'?[3,7,14,30][level-1]:value==='hard'?1:0;store.srs[c.id]={level,due:Date.now()+days*86400000,last:Date.now()};store.reviews[c.id]=Date.now();track('review',c,{rating:value});if(value==='again'){session.queue.push(c);if(session.queue.length-session.index>2){const last=session.queue.pop();session.queue.splice(Math.min(session.index+3,session.queue.length),0,last)}}session.index++;session.revealed=false;save();render();}
function practice(){const list=cards(current()).filter(c=>practiceType==='word'?c.type==='word':practiceType==='example'?c.type==='example':c.type==='phrase');const correct=list.filter(c=>store.practice[dayKey(c.id)]);const target=list.find(c=>!store.practice[dayKey(c.id)]);return hero('PRACTICE','從看得懂，到說得出。','聽寫涵蓋 Today 全部 13 項；答對才列入完成。')+`<div class="tabs">${[['word','單字 5'],['example','例句 5'],['phrase','回答句 3'],['speaking','口說']].map(([id,label])=>`<button data-practicetype="${id}" class="${practiceType===id?'selected':''}">${label}</button>`).join('')}</div>${practiceType==='speaking'?speaking():`<section class="card"><div class="row"><h2>${typeLabel[practiceType]}聽寫</h2><span class="chip">${correct.length} / ${list.length} 完成</span></div><div class="progress"><span style="width:${correct.length/list.length*100}%"></span></div>${target?`<p>第 ${list.indexOf(target)+1} 題：先聽，再輸入英文。</p><button class="icon primary" data-audio="${esc(target.en)}" aria-label="播放聽寫題目">${svg('audio')}</button><button data-action="slow">${store.slow?'慢速':'正常'}</button><label for="dictation">你的答案</label><textarea id="dictation" rows="3" autocapitalize="none" autocomplete="off" spellcheck="false"></textarea><div class="wrap"><button class="primary" data-check="${target.id}">檢查答案</button><button data-hint="${target.id}">提示</button></div><p id="feedback" role="status"></p><p class="caption">不計大小寫及標點；拼字和字序必須正確。答錯後可繼續修改。</p>`:'<div class="empty"><h2>這一組已全部完成。</h2><p>換下一組，或重新練習。</p></div>'}<button data-restartpractice="${practiceType}">重新練這一組</button></section><section class="card"><h3>今日完整清單</h3>${list.map((c,i)=>`<p>${i+1}. ${esc(c.zh)} <span class="chip">${store.practice[dayKey(c.id)]?'已答對':'待練習'}</span></p>`).join('')}</section>`}`}
function speaking(){const t=getTopic(),checks=store.confidence[t.id]||[];return `<section class="card"><div class="eyebrow">${esc(t.title)}</div><h2>${esc(t.q)}</h2><p>${esc(t.qzh)}</p><details><summary>查看我的回答與示範</summary><p>${esc(store.answers[t.id]||'你還沒寫自己的回答，可以先練示範。')}</p>${unit(cardFor(`${t.id}:answer:${difficulty}`))}</details><p class="notice">目標：基礎版 30 秒、進階版 60–90 秒。計時不等於能力評分。</p><div class="wrap"><button data-action="record" class="primary" id="recordButton">${recording?'停止錄音':'錄音練習'}</button><span id="recordTime">${recordSeconds} 秒</span></div><audio id="playback" controls ${recordUrl?`src="${recordUrl}"`:'class="hidden"'}></audio><p class="caption">錄音只在本次頁面保留，不上傳。開始時需允許麥克風。可下載錄音自行保存。</p>${recordUrl?`<a href="${recordUrl}" download="interview-practice.${recordExtension}" class="link">下載本次錄音</a>`:''}<div class="checklist">${['我能不看稿回答','我說清楚自己的貢獻','我能回答一個追問'].map((label,i)=>`<label><input type="checkbox" data-confidence="${i}" ${checks.includes(i)?'checked':''}>${label}</label>`).join('')}</div><p class="caption">這是自我檢核，沒有自動發音或面試評分。</p><details><summary>追問練習題</summary>${unit(cardFor(t.id+':follow'))}${unit(cardFor(t.id+':reply'))}</details><div class="wrap"><button data-action="logSpeaking">完成一次口說練習</button><button data-action="logFollowup">完成一次追問練習</button></div><p class="caption">無須錄音也能手動記錄；成功錄音會自動記一次，同次練習不需再按完成。</p></section>`}
function plan(){let old={};try{old=JSON.parse(localStorage.getItem(OLD)||'{}')}catch{}return hero('MY PLAN','練習有方向，面試有底氣。','14 組核心題目，以不同輪次累積理解、脫稿表達與追問能力。')+`<section class="card focus"><div class="eyebrow">LEARNING JOURNEY</div><h2>學習歷程</h2><p>日曆、聽寫表現、熟悉程度與下一步練習。</p><button class="primary" data-page="history">查看我的學習歷程</button></section><div class="metrics card"><div><strong>${Object.keys(store.bookmarks).length}</strong><small>收藏重點</small></div><div><strong>${Object.values(store.confidence).filter(v=>v.length===3).length} / 14</strong><small>三項自評皆完成</small></div><div><strong>${Object.keys(store.practice).length}</strong><small>聽寫答對項目</small></div></div><section class="card"><h2>選擇準備節奏</h2><label for="route">學習路線</label><select id="route">${[[14,'14 天衝刺 · 每天一個核心題'],[30,'30 天準備 · 核心題反覆練習與追問'],[90,'90 天提升 · 分輪跟讀、脫稿與進階表達']].map(([n,s])=>`<option value="${n}" ${store.route===n?'selected':''}>${s}</option>`).join('')}</select><p class="caption">路線共用 14 組題庫，後續天數是刻意複習，不是全新題目。切換路線保留收藏、答案與進度。</p><label for="interviewDate">面試日期（選填）</label><input id="interviewDate" type="date" value="${esc(store.interviewDate)}"><label for="daySelect">跳到學習日</label><select id="daySelect">${Array.from({length:store.route},(_,i)=>`<option value="${i}" ${i===store.day?'selected':''}>Day ${i+1} · ${topics[i%14].title} · 第 ${Math.floor(i/14)+1} 輪</option>`).join('')}</select></section><section class="card"><h2>我的面試準備</h2><div class="topicList">${topics.map((t,i)=>`<button data-open-topic="${t.id}"><div class="topicIndex">${String(i+1).padStart(2,'0')} / ${t.category}</div>${t.title}<small>${store.answers[t.id]?'已有個人回答':'尚未寫個人回答'} · 自評 ${(store.confidence[t.id]||[]).length}/3</small></button>`).join('')}</div></section><section class="card"><h2>備份與帶走紀錄</h2><p>收藏、個人回答與複習排程保存在此裝置／瀏覽器。清除網站資料會移除紀錄，建議定期匯出。</p><div class="wrap"><button data-action="export">匯出學習紀錄</button><button data-action="import">匯入紀錄（合併）</button><input type="file" id="importFile" accept="application/json,.json" hidden></div><p class="caption">匯入只新增缺少的內容，不覆蓋本機已有回答與排程。檔案包含個人回答，請自行妥善保存。</p>${Object.keys(old).length?'<p class="notice">舊版 90 天學習紀錄已原樣保留，匯出時會一併備份。</p>':''}${storageWarning?'<p>目前無法寫入裝置儲存，請先匯出。</p>':''}</section><section class="card"><h3>安裝到手機</h3><p>Safari 分享 → 加入主畫面。首次連網開啟後，可離線讀取內建課程與收藏。英文發音取決於裝置可用語音。</p><small>Interview Studio · v8</small></section>`}
function render(){navigation();$('#view').innerHTML=({today,interview,review,practice,plan,history}[page])();$('#onlineStatus').textContent=navigator.onLine?'本機保存':'離線模式';}
function openPage(p){if(recording||recordPending)return toast('請先停止錄音再切換頁面。');stopSpeech();session=null;page=p;render();window.scrollTo({top:0,behavior:'instant'})}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
if(d.month){const [y,m]=historyMonth.split('-').map(Number);historyMonth=localDay(new Date(y,m-1+Number(d.month),1)).slice(0,7);historyDate=historyMonth===localDay().slice(0,7)?localDay():historyMonth+'-01';render();return}
if(d.historyDate){historyDate=d.historyDate;render();return}
if(d.historyDue){reviewSource='due';reviewType='all';return openPage('review')}
if(d.historyPractice){store.day=Number(d.courseDay);if(store.route<=store.day)store.route=90;topicId=current().id;const c=cardFor(d.historyPractice);practiceType=c?.type||'word';difficulty=store.day>=28?'advanced':'basic';if(c)delete store.practice[dayKey(c.id)];save();return openPage('practice')}
if(d.historyReview){const c=cardFor(d.historyReview);if(!c)return toast('這筆內容已不在題庫或收藏中。');openPage('review');session={queue:[c],unique:[c.id],index:0,revealed:false};render();return}
if(d.word)return lookup(d.word,b.closest('[data-context]')?.dataset.context);if(d.audio)return speak(d.audio,b);if(d.bookmark)return bookmark(d.bookmark);if(d.page)return openPage(d.page);if(d.openTopic){topicId=d.openTopic;return openPage('interview')}if(d.day!==undefined){store.day=Math.max(0,Math.min(store.route-1,+d.day));topicId=current().id;difficulty=Math.floor(store.day/14)>=2?'advanced':'basic';save();return openPage('today')}if(d.learned){store.learned[dayKey(d.learned)]=!store.learned[dayKey(d.learned)];if(store.learned[dayKey(d.learned)])track('read',cardFor(d.learned));save();render();return}if(d.difficulty){difficulty=d.difficulty;render();return}if(d.source){reviewSource=d.source;session=null;render();return}if(d.reviewtype){reviewType=d.reviewtype;session=null;render();return}if(d.rating)return rate(d.rating);if(d.practicetype){if(recording||recordPending)return toast('請先停止錄音。');practiceType=d.practicetype;render();return}if(d.restartpractice){cards(current()).filter(c=>c.type===d.restartpractice).forEach(c=>delete store.practice[dayKey(c.id)]);save();render();return}if(d.check){const c=cardFor(d.check);const norm=s=>s.toLowerCase().replace(/[^a-z0-9\s]/g,'').replace(/\s+/g,' ').trim();const entered=norm($('#dictation').value);if(!entered){$('#feedback').textContent='請先輸入答案。空白不列入作答紀錄。';return}const correct=entered===norm(c.en);track('dictation',c,{correct});save();if(correct){store.practice[dayKey(c.id)]=Date.now();save();toast('答對了，已加入完成進度。');render()}else $('#feedback').textContent='再試一次。可以按提示，或重新聽一遍。';return}if(d.hint){const c=cardFor(d.hint);$('#feedback').textContent=`${c.zh} · 提示：${c.en.split(' ').map(w=>w[0]+'＿'.repeat(Math.max(0,w.length-1))).join(' ')}`;return}const a=d.action;if(a==='logSpeaking'||a==='logFollowup'){track(a==='logSpeaking'?'speaking':'followup');save();b.disabled=true;toast('已記錄到學習歷程。');return}if(a==='slow'){store.slow=!store.slow;save();if($('#dictation')){b.textContent=store.slow?'慢速':'正常';return}render()}if(a==='startReview'){const pool=reviewPool();session={queue:pool.slice(),unique:pool.map(c=>c.id),index:0,revealed:false};render()}if(a==='reveal'){session.revealed=true;render()}if(a==='endReview'){session=null;render()}if(a==='goSpeaking'){practiceType='speaking';openPage('practice')}if(a==='saveLookup'&&translation){store.bookmarks[translation.id]={...translation,savedAt:Date.now()};save();toast('已加入我的重點');$('#wordDialog').close()}if(a==='export')exportData();if(a==='import')$('#importFile').click();if(a==='record')await record();});
$('#closeWord').onclick=()=>$('#wordDialog').close();
document.addEventListener('input',e=>{if(e.target.id==='personalAnswer'){store.answers[getTopic().id]=e.target.value;save()}});
document.addEventListener('change',e=>{const el=e.target;if(el.id==='personalAnswer'&&el.value.trim()){track('answer');save()}if(el.id==='topicSelect'){topicId=el.value;render()}if(el.id==='route'){store.route=+el.value;store.day=Math.min(store.day,store.route-1);topicId=current().id;difficulty=store.day>=28?'advanced':'basic';save();render()}if(el.id==='daySelect'){store.day=+el.value;topicId=current().id;difficulty=store.day>=28?'advanced':'basic';save();openPage('today')}if(el.id==='interviewDate'){store.interviewDate=el.value;save();render()}if(el.dataset.confidence!==undefined){const id=getTopic().id;const set=new Set(store.confidence[id]||[]);el.checked?set.add(+el.dataset.confidence):set.delete(+el.dataset.confidence);store.confidence[id]=[...set];track('selfcheck');save()}if(el.id==='importFile')importData(el.files[0]);});
function exportData(){let legacy=null;try{legacy=JSON.parse(localStorage.getItem(OLD)||'null')}catch{}const blob=new Blob([JSON.stringify({app:'id-interview-studio',version:1,exportedAt:new Date().toISOString(),data:store,legacy},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`id-english-backup-${dateStamp()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
async function importData(file){if(!file)return;try{if(file.size>5*1024*1024)throw Error();const v=JSON.parse(await file.text());if(v.app!=='id-interview-studio'||v.version!==1||!v.data||Array.isArray(v.data))throw Error();const maps=['bookmarks','answers','srs','reviews','practice','confidence','learned'];for(const k of maps){const map=v.data[k];if(!map||typeof map!=='object'||Array.isArray(map))throw Error();for(const [id,value]of Object.entries(map)){if(['__proto__','constructor','prototype'].includes(id)||id.length>200)throw Error();if(k==='bookmarks'&&(!value||!['id','type','en','zh','source'].every(f=>typeof value[f]==='string')||value.id!==id||value.en.length>12000))throw Error();if(k==='answers'&&typeof value!=='string')throw Error();if(k==='srs'&&(!value||!Number.isFinite(value.due)||!Number.isInteger(value.level)||value.level<0||value.level>4))throw Error();if(k==='confidence'&&(!Array.isArray(value)||value.some(n=>![0,1,2].includes(n))))throw Error();if(['reviews','practice'].includes(k)&&!Number.isFinite(value))throw Error();if(k==='learned'&&typeof value!=='boolean')throw Error();}}
 if(v.data.history!==undefined&&!validHistory(v.data.history))throw Error();
 for(const [id,value]of Object.entries(v.data.history||{}))if(!Object.hasOwn(store.history,id))store.history[id]=value;
 if(validDay(v.data.historyStarted)&&v.data.historyStarted<store.historyStarted)store.historyStarted=v.data.historyStarted;
 for(const k of maps)for(const [id,value]of Object.entries(v.data[k]))if(!Object.hasOwn(store[k],id))store[k][id]=value;if(v.legacy&&!localStorage.getItem(OLD))localStorage.setItem(OLD,JSON.stringify(v.legacy));save();toast('已合併備份；本機已有內容保持不變。');render();}catch{toast('無法匯入：請選擇此 App 匯出的有效備份。')}}
async function record(){if(recordPending)return;if(recording){recording.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return toast('此瀏覽器無法錄音，可用手機錄音功能練習。');let stream;recordPending=true;try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[];recording=new MediaRecorder(stream);recordSeconds=0;recording.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recording.onstop=()=>{const mime=recording.mimeType;recordExtension=mime.includes('mp4')?'m4a':mime.includes('ogg')?'ogg':'webm';stream.getTracks().forEach(t=>t.stop());clearInterval(recordTimer);if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=URL.createObjectURL(new Blob(chunks,{type:mime}));recording=null;if(chunks.length&&recordSeconds>0){track('speaking');save()}render()};recording.start();render();recordTimer=setInterval(()=>{recordSeconds++;if($('#recordTime'))$('#recordTime').textContent=recordSeconds+' 秒';if(recordSeconds>=180&&recording?.state==='recording')recording.stop()},1000)}catch{stream?.getTracks().forEach(t=>t.stop());recording=null;toast('未能取得麥克風。你仍可跟讀並完成自評。')}finally{recordPending=false}}
window.addEventListener('online',()=>$('#onlineStatus').textContent='本機保存');window.addEventListener('offline',()=>$('#onlineStatus').textContent='離線模式');window.addEventListener('pagehide',()=>{if(recording?.state==='recording')recording.stop();stopSpeech()});
save();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{if(!navigator.serviceWorker.controller)toast('尚未完成離線準備，請連網開啟一次。')});
// Keep content and toasts above the real navigation height, including text zoom.
if('ResizeObserver' in window){new ResizeObserver(entries=>{const h=entries[0]?.borderBoxSize?.[0]?.blockSize||document.querySelector('#nav').getBoundingClientRect().height;document.documentElement.style.setProperty('--nav-height',h+'px')}).observe(document.querySelector('#nav'));}
