import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto as crypto} from 'node:crypto';
import {localDay,validDay,validHistory,historyView,eventList,dayStats,dictationStats} from './learning-history.js';
import {topics,commonGlossary,extraGlossary,phraseTranslations} from './interview-content.js';
const listeners={},elements=new Map();
const element=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',dataset:{},classList:{remove(){},add(){}},setAttribute(){},removeAttribute(){},showModal(){},close(){}});return elements.get(id)};
const data=new Map([['idInterviewEnglishState',JSON.stringify({day:22,bookmarks:['legacy']})]]);
const ctx=vm.createContext({crypto,localDay,validDay,validHistory,historyView,topics,commonGlossary,extraGlossary,phraseTranslations,console,Date,URL,Blob,Set,localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},document:{querySelector:element,querySelectorAll:()=>[],addEventListener:(k,f)=>listeners[k]=f},window:{addEventListener(){},scrollTo(){}},navigator:{onLine:true},setTimeout:()=>0,clearTimeout(){}});
vm.runInContext(fs.readFileSync(new URL('./studio.js',import.meta.url),'utf8').replace(/^import[^\n]+\n/gm,''),ctx);
const run=s=>vm.runInContext(s,ctx);
assert.equal(topics.length,14);assert.equal(run('allCards().length'),252);
for(const t of topics){assert.equal(t.vocab.length,5);assert.equal(phraseTranslations[t.id].length,3);assert.equal(run(`cards(topics.find(t=>t.id==='${t.id}')).length`),13);}
const dict={...commonGlossary,...extraGlossary};for(const t of topics)for(const v of t.vocab)dict[v[0]]=v[1];
const missing=new Set();for(const t of topics)for(const s of [t.q,t.basic,t.advanced,t.follow,t.reply,...t.vocab.flatMap(v=>[v[0],v[2]])])for(const w of s.toLowerCase().match(/[a-z]+(?:[-'][a-z]+)*/g)||[])if(!dict[w]&&![w.replace(/s$/,''),w.replace(/ies$/,'y'),w.replace(/ed$/,''),w.replace(/d$/,''),w.replace(/ing$/,''),w.replace(/ing$/,'e')].some(x=>dict[x]))missing.add(w);
assert.deepEqual([...missing],[],'All authored dialogue words have Chinese lookup');
run("bookmark('intro:word:0');store.day=1;reviewSource='saved'");assert.equal(run('reviewPool().length'),1);assert.equal(run('reviewPool()[0].en'),'designer');
run("reviewSource='due';startReview();session.revealed=true;rate('good')");assert.equal(run('reviewPool().length'),0);assert.equal(run("store.srs['intro:word:0'].level"),1);assert.equal(run('Object.keys(store.bookmarks).length'),1);
run("reviewSource='saved';startReview();session.revealed=true;rate('again')");assert.equal(run('session.queue.length'),2);assert.equal(run('session.queue[1].id'),run('session.queue[0].id'));
run("session.revealed=true;rate('hard')");assert.equal(run('store.srs[session.queue[1].id].level'),0);
run("store.day=0;store.practice[dayKey('intro:word:0')]=1;store.day=14");assert.equal(run("store.practice[dayKey('intro:word:0')]"),undefined);
assert.deepEqual(JSON.parse(data.get('idInterviewEnglishState')),{day:22,bookmarks:['legacy']});
const backup=JSON.parse(data.get('idEnglishStudio.v1'));backup.answers.intro='Imported answer';
await run(`importData({size:100,text:async()=>${JSON.stringify(JSON.stringify({app:'id-interview-studio',version:1,data:backup}))}})`);assert.equal(run('store.answers.intro'),'Imported answer');
run("store.answers.intro='Local answer'");await run(`importData({size:100,text:async()=>${JSON.stringify(JSON.stringify({app:'id-interview-studio',version:1,data:backup}))}})`);assert.equal(run('store.answers.intro'),'Local answer');
console.log('PASS: 14 topics, 182 daily units, 252 total cards, full word lookup, bookmark persistence, SRS, repeated-day practice, backup merge and legacy preservation.');
assert.equal(run('store.historyStarted'),localDay());
const beforeNavigation=run('Object.keys(store.history).length');
run("openPage('history');store.day=29;openPage('today')");
assert.equal(run('Object.keys(store.history).length'),beforeNavigation);
run("store.day=0");
const click=dataset=>listeners.click({target:{closest:()=>({dataset})}});
await click({learned:'intro:word:0'});await click({learned:'intro:word:0'});await click({learned:'intro:word:0'});
assert.equal(run("Object.values(store.history).filter(e=>e.kind==='read').length"),1);
const beforeEmpty=run('Object.keys(store.history).length');
element('#dictation').value='';await click({check:'intro:word:0'});assert.equal(run('Object.keys(store.history).length'),beforeEmpty);
element('#dictation').value='wrong';await click({check:'intro:word:0'});
element('#dictation').value='designer';await click({check:'intro:word:0'});
element('#dictation').value='useful';await click({check:'intro:word:1'});
const events=eventList(JSON.parse(run('JSON.stringify(store.history)')));
assert.deepEqual(dictationStats(events),{total:3,correct:2,first:2,firstCorrect:1,retries:1});
assert.equal(dayStats(events).dictation,2);
assert.equal(validHistory(JSON.parse(run('JSON.stringify(store.history)'))),true);
const exported=JSON.parse(run('JSON.stringify(store)'));
const loadBackup=async data=>run(`importData({size:100,text:async()=>${JSON.stringify(JSON.stringify({app:'id-interview-studio',version:1,data}))}})`);
const count=run('Object.keys(store.history).length');
await loadBackup(exported);await loadBackup(exported);
assert.equal(run('Object.keys(store.history).length'),count);
delete exported.history;delete exported.historyStarted;await loadBackup(exported);
assert.equal(run('Object.keys(store.history).length'),count,'v7 imports do not erase history');
assert.equal(validDay('2026-02-30'),false);assert.equal(validDay('2028-02-29'),true);
const invalid={...exported,history:{bad:{id:'bad',kind:'dictation',date:'bad'}}};await loadBackup(invalid);
assert.equal(run('Object.keys(store.history).length'),count,'invalid import is rejected before mutation');
const rendered=run("history()");
assert.ok(rendered.includes('學習日曆')&&rendered.includes('50%'));
assert.ok(!rendered.includes('最近仍答錯：designer'),'resolved mistakes no longer suggested');
console.log('PASS: activity-only history, deduplicated reads, blank answer exclusion, first-attempt accuracy, retries, idempotent backups, v7 compatibility and calendar date validation.');
run("store.bookmarks={};reviewMode='flash';reviewSource='saved';session=null");
assert.equal(run('reviewPool().length'),0,'No unmarked course cards');
assert.ok(run('review()').includes('先收藏'));
run("bookmark('intro:word:0');bookmark('intro:example:0');store.day=7;reviewMode='spell'");
assert.equal(run('reviewPool().length'),1);
assert.equal(run('reviewPool()[0].type'),'word');
run("reviewMode='cloze'");
assert.equal(run('reviewPool().length'),1);
assert.equal(run("cloze(reviewPool()[0]).answer"),'designer','Prefer bookmarked word');
assert.ok(!run("cloze(reviewPool()[0]).before+cloze(reviewPool()[0]).after").includes('designer'));
run("reviewMode='flash';startReview()");
assert.equal(run('session.queue.length'),2);
assert.ok(run('reviewSession()').includes('designer'));
assert.ok(!run('reviewSession()').includes('設計師'),'Flash hides translation before reveal');
run("session.revealed=true;rate('again')");
assert.equal(run('session.queue.length'),3);
assert.equal(run("session.results['intro:word:0'].first"),'again');
run("reviewMode='spell';startReview()");
const beforeReview=run('Object.keys(store.history).length');
element('#reviewAnswer').value='';run('checkReview()');
assert.equal(run('session.checked'),false);
assert.equal(run('Object.keys(store.history).length'),beforeReview);
element('#reviewAnswer').value='wrong';run('checkReview()');
assert.equal(run('session.correct'),false);
await click({action:'nextReview'});
assert.equal(run('session.queue.length'),2);
element('#reviewAnswer').value=' DESIGNER ';run('checkReview()');
assert.equal(run('session.correct'),true);
await click({action:'nextReview'});
assert.equal(run('session.index'),2);
assert.ok(run('reviewSession()').includes('需要加強 · 1 項'));
run("reviewMode='cloze';startReview()");
element('#reviewAnswer').value=run('cloze(session.queue[0]).answer');
await click({action:'reviewHint'});run('checkReview()');await click({action:'nextReview'});
assert.equal(run("store.srs['intro:example:0'].level"),0,'Assisted answer schedules tomorrow');
assert.ok(run("store.srs['intro:example:0'].due")>Date.now()+23*3600000);
run("reviewSource='due';reviewMode='cloze'");assert.equal(run('reviewPool().length'),0);
run("bookmark('intro:word:0');session=null");
await click({historyReview:'intro:word:0'});assert.equal(run('session'),null,'History cannot revive unmarked card');
assert.equal(validHistory(JSON.parse(run('JSON.stringify(store.history)'))),true);
console.log('PASS: saved-only pools, three modes, cloze, flash reveal, empty input, retry, hint scheduling and removed-bookmark history guard.');
run("reviewSource='saved';reviewMode='cloze';startReview()");
assert.ok(run('reviewSession()').includes('value=""'),'Answer field begins empty');
element('#reviewAnswer').value='wrong';
const reviewEventsBefore=run("Object.values(store.history).filter(e=>e.kind==='review').length");
run('checkReview()');
assert.ok(run('reviewSession()').includes('value="wrong"'),'Keep submitted answer visible');
assert.equal(run("Object.values(store.history).filter(e=>e.kind==='review').length"),reviewEventsBefore+1,'Submission persists before Next');
await click({action:'nextReview'});
assert.equal(run("Object.values(store.history).filter(e=>e.kind==='review').length"),reviewEventsBefore+1,'Next never records twice');
